spring:
  profiles:
    active: local

---
server:
  port: 3000

spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/day_book
    username: root
    password: fixel12!@
