spring:
  profiles:
    active: local

---
server:
  port: ${PORT:8080}

spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daybook-db
    username: postgres
    password: root
    platform: postgres
